name: webrtsp-record-streamer
base: core24
summary: WebRTSP server remote Agent
description: |
  Intended to record RTSP streams from IP Cams (and some other URL types) to WebRTSP server (for example to https://snapcraft.io/rtsp-to-webrtsp).
  Can be used as part of Cloud NVR (https://github.com/WebRTSP/ReStreamer#how-to-use-it-as-cloud-nvr-for-ip-cam-not-accessible-directly)

  **Config file location:** /var/snap/webrtsp-record-streamer/common/record-streamer.conf
license: GPL-3.0
grade: devel
confinement: strict
adopt-info: recorder

platforms:
  amd64:
  arm64:

environment:
  GST_DEBUG: 2
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

layout:
  /opt/webrtsp-record-streamer/lib:
    symlink: $SNAP/opt/webrtsp-record-streamer/lib

parts:
  recorder:
    plugin: cmake
    source-type: git
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME} -DUSE_LIBMICROHTTPD=NO
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    build-packages:
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - gsoap
      - libgsoap-dev
      - libnice-dev
      - libmicrohttpd-dev
      - libwebsockets-dev
    stage-packages:
      - libconfig9
      - libslang2
      - libspdlog1.12
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-nice
      - libgsoap-2.8.132t64
      - libnice10
      - libmicrohttpd12
      - libwebsockets19t64
      - libwebsockets-evlib-glib

apps:
  RecordStreamer:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/RecordStreamer
    daemon: simple
    plugs:
      - network
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$LD_LIBRARY_PATH
